const images = {
  LOGO: require('../assets/images/logo.png'),
  TS: require('../assets/images/ts.png'),
  LOGIN: require('../assets/images/login.png'),
  PICTURE: require('../assets/images/profile.png'),
  MATERI: require('../assets/images/materi.png'),
  latihan: require('../assets/images/latihan.png'),
  ambil: require('../assets/images/ambil.png'),
  about: require('../assets/images/about.png'),
  BENAR: require('../assets/images/benar.png'),
  SALAH: require('../assets/images/salah.png'),
  QUIZ_ICON: require('../assets/images/quiz_icon.png'),
  A: require('../assets/images/A.jpg'),
  WD: require('../assets/images/WD.jpg'),
  WJ: require('../assets/images/WJ.jpg'),
  V: require('../assets/images/V.jpg'),
  R: require('../assets/images/R.jpg'),
  bab1: require('../assets/images/1.png'),
  bab2: require('../assets/images/2.png'),
  bab3: require('../assets/images/3.png'),
  bab4: require('../assets/images/4.png'),
  bab5: require('../assets/images/5.png'),
  bab6: require('../assets/images/6.png'),
  bab7: require('../assets/images/7.png'),
  bab8: require('../assets/images/8.png'),
  bab9: require('../assets/images/9.png'),
  bab10: require('../assets/images/bab1.png'),
  FB: require('../assets/images/FB.png'),
  PN: require('../assets/images/PN.png'),
  TWT: require('../assets/images/TWT.png'),
  IG: require('../assets/images/IG.png'),
  LD: require('../assets/images/LD.png'),
  ST: require('../assets/images/ST.png'),
};

export default images;
